results_dir: /workspace/train/results/

model:
  backbone:
    type: fan_small_12_p4_hybrid
    pretrained_backbone_path: /workspace/train/pretrained_fan_classification_imagenet_vfan_hybrid_small/fan_hybrid_small.pth
    freeze_backbone: True
  head:
    type: TAOLinearClsHead
    binary: false
    in_channels: 512
    topk: [1]

dataset:
  dataset: CLDataset
  root_dir: /workspace/data/
  num_classes: 3
  img_size: 224
  batch_size: 9
  workers: 4
  augmentation:
    mixup_cutmix: false
    random_flip:
      enable: true
      hflip_probability: 0.5
      vflip_probability: 0.0
    random_aug:
      enable: true
    random_erase:
      enable: true
    random_rotate:
      enable: false
    random_color:
      enable: false
    with_scale_random_crop:
      enable: true
    with_random_crop: false
    with_random_blur: true
  train_dataset:
    images_dir: /workspace/data/train
  val_dataset:
    images_dir: /workspace/data/val
  test_dataset:
    images_dir: /workspace/data/test

evaluate:
  checkpoint: /workspace/train/results/train/classifier_model_latest.pth