results_dir: /workspace/train/results/

model:
  backbone:
    type: resnet_18
    pretrained_backbone_path: null
    freeze_backbone: false
  head:
    type: TAOLinearClsHead
    binary: false
    in_channels: 512
    topk: [1]

dataset:
  dataset: CLDataset
  root_dir: /workspace/data/
  num_classes: 2
  img_size: 224
  batch_size: 6
  workers: 4
  augmentation:
    mixup_cutmix: false
    random_flip:
      enable: false
      hflip_probability: 0.0
      vflip_probability: 0.0
    random_aug:
      enable: false
    random_erase:
      enable: false
    random_rotate:
      enable: false
    random_color:
      enable: false
    with_scale_random_crop:
      enable: false
    with_random_crop: false
    with_random_blur: true
  train_dataset:
    images_dir: /workspace/data/train
  val_dataset:
    images_dir: /workspace/data/val
  test_dataset:
    images_dir: /workspace/data/test

train:
  num_gpus: 1
  gpu_ids: [0]
  num_epochs: 30
  validation_interval: 1
  checkpoint_interval: 1
  pretrained_model_path: null
  optim:
    optim: sgd
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0001